### PR TITLE
WIP - Add Divergent Paths: Medic

### PR DESCRIPTION
**Pull request by drumanagh**
This is a first pass at adding the content from *Divergent Paths: Medic*: the Medic class, four archetypes, and a small set of supporting feats and magic items. Since I barely know what I'm doing with Hero Lab's tangling sprawl of XML stuff and did most of this in the editor, I'd appreciate a review and help with tuning up things to work properly before actually looking at a merge.

## Known problems

**Medic:**
- [x] The class isn't actually adding maneuvers. I'm not sure why, but it should hopefully be something easy to fix by somebody who knows what they're doing.

**Archetypes:**
- [ ] Ambu-Lancer (ar3PAmbLan) should lose Tempest Gale and gain Piercing Thunder.
- [ ] Angel of Mercy (ar3PAnMerc) should lose Broken Blade and gain Silver Crane.

**Class features:**
- [ ] Triage (cMdcTriage) is using `xIndex`, but it needs to use something else that accounts for level-listing items disabled with `Helper.SpcDisable`.
- [ ] Improved Triage (cMdcImpTri) is using `xIndex`, but it needs to use something else that accounts for level-listing items disabled with `Helper.SpcDisable`.
- [ ] Blood Transfusion (cMdcBloTra) should use medic initiation modifier instead of Wisdom.
- [ ] Unnatural Vitality (cMdcUnnVit) should use medic initiation modifier instead of Wisdom.
- [ ] Barefisted Syringe (cMdcBarSyr) should use medic initiator level instead of class level.
- [ ] Bolstering Strikes (cMdcBolStr) should use medic initiator level instead of class level.
- [ ] Pain's Gain (cMdcPaiGai) needs to give an untyped attack/damage bonus to all unarmed strikes and natural attacks.
- [ ] Magical Assistance (cMdcMagAss) should add a wand at first level... if that's even possible.
- [ ] Magical Understanding (cMdcMagUnd) should qualify for item creation feats using medic initiator level instead of caster level. This one... I don't even know where to start. I tried piggybacking on what Master Craftsman does and adding the tags to the player that it does, but I couldn't get that to work.
- [x] Witch Doctor Skills (cMdcWitSki) should make the character use Wisdom instead of Intelligence for Spellcraft checks, and Wisdom instead of Charisma for Use Magic Device checks.
- [ ] Mount (cMdcMount) needs to work like animal companion (despite the name), but with a limited list of options and with Light Armor Proficiency automatically granted to the companion. Not sure how to put thise one together.
- [ ] Siren (cMdcSiren) needs to give the mount from cMdcMount the Improved Overrun feat, but only when the second activation for Siren is activated ("mounted and using Triage" or similar).

**Feats:**
- [ ] First Aid Training (f3PFirsAid) should be setting abValue based on Wis modifier and Heal ranks, but I can't get that to work for some reason.
- [ ] Gungnir Technique (f3PGungTec) should give all equipped polearms and spears *ghost touch*, but only while in a Silver Crane stance. I'm not sure even where to start to make that work.
- [ ] Nemean Lion Hide (f3PNemLion) should give DR equal to highest initiation modifier when activated. Also not sure where to even start with that.

## Philosophical weirdness

- [ ] Thaumaturgic Medicine (cMdcThaMed) grants a spell list, but *not* any casting capability (so you can use magic items, etc). Is this something that would get any benefit in HL from trying to implement, or is it better off just leaving it as a text list?

## Still missing

- [ ] Favored class options. I'll be adding those in another pass on the same branch.

### CODE REVIEW

**Comment by drumanagh** [comment]
With more testing and pokery I've fixed the lack of maneuvers for Medic and the skill ability swaps for Witch Doctor Skills.

**Comment by shadowchemosh** [comment]
So I admit. I am not an expert with GitHub yet.  I tried to make some changes to this pull but instead it created a whole new branch.

https://github.com/shadowchemosh/HL-Pack-Pathfinder/tree/pr/84

**Comment by psych777** [comment]
do i dare open sourcetree yet? or do i need to wait if you need to fix something? :o)


________________________________

**Comment by shadowchemosh** [comment]
Feel free. These changes are currently setup as it's own isolated Branch. So feel free to open sourcetree.

**Comment by drumanagh** [comment]
> So I admit. I am not an expert with GitHub yet. I tried to make some changes to this pull but instead it created a whole new branch.

No problem, I merged that back into the original branch so it'll show up on the PR. Thanks so much for going through things!

> do i dare open sourcetree yet? or do i need to wait if you need to fix something? :o)

I'll second, feel free to dig into things.

**Comment by drumanagh** [comment]
Also, to add a note - I plan to add these changes to pickreq, source, etc, to my other PRs so that @shadowchemosh won't have to do that again, but since I'm having [a bit of trouble with testing things in HL](http://forums.wolflair.com/showpost.php?p=242820&postcount=2) that might take some time.

@shadowchemosh, one side question - why add "DSP" to the title of the sources? I'm not really clear on why that's there in the first place, since it's inconsistent with some other stuff in the 3PP pack (e.g. MSRD, Eberron).

**Comment by shadowchemosh** [comment]
@drumanagh I know we have some inconsistent naming conventions going on.  Such issues often happen with such a dynamic growth we have had in this software.  I would like to make it consistent and its a work in progress.

The idea is that "DSP" lets people know "Dreamscarred Press" did the specific source/book and that the book can be found under the new "Dreamscarred Press" parent source. This is similar to how if you look at "Advanced Player's Guide" as a parent and then each "child" source repeats the name "advanced players guide". This is because only the 'child' source name gets displayed in the different lists.

**Comment by shadowchemosh** [comment]
@drumanagh did Colen get your HL fixed yet?

**Comment by drumanagh** [comment]
FYI, this still has some stuff that needs fixing and that I've been too distracted by RL lately to work on, thus the unchecked checkboxes in the first post.

Edit: Unless you already went through those yourself, anyway.

**Pull request merged**
