### PR TITLE
Add content from Psionics Augmented: Seventh Path

### PR DESCRIPTION
**Pull request by drumanagh**
This adds everything but the monsters from *Psionics Augmented: Seventh Path*. To try and keep 40-odd pages worth of content actually reviewable, I broke things up into a couple of files, but I'm not entirely sure on your preferences there so I can rearrange things if wanted.

Known bugs:

- [ ] Spirit Road (`cPWaSpiRoa` in the archetypes file) and Ghost Road (`cPWaGhoRoa` in the archetypes file) aren't currently implemented, since I'm not sure how to make the listed effect actually work right.
- [ ] Prereqs for Gravebound (`arPsAuGrav` in the archetypes file) and Phantom (`arPsAuPhan` in the archetypes file) are totally broken, because those are in the bizarro state of being prestige class archetypes with different prereqs than the original prestige class and I'm not sure if it's even possible to implement that properly.
- [ ] Hounforge (`arPsiHounf` in the archetypes file) needs to subtract half the Psion level from the effective level for its eidolon, but I can't figure out how to adjust that to make it work.
- [ ] The Cerebric Guardian feat isn't currently implemented, since I wasn't sure of a sane way to make it work. It says so in the feat text, though, and I think that might be fine for now since its effects are tangential to real stats.

Aside from those, I should have it all working already, hopefully.

### CODE REVIEW

**Comment by shadowchemosh** [comment]
First this is HOLY cow allot of work.  Thanks so much for this.  I will need to pick up this PDF as I have not heard of it before. =)

I do like keeping things broken down into different files.  That makes thing much more manageable.  Thanks!

Looking this over quick the first thing that I see we need to fix is the Unique ID's.  We need "PU" in all Unique ID's.  In example rcPsAuAMan has to become rcPUAuAMan.  This adding the PU may seem stupid but its vital to prevent the Pack from clashing with LW stuff.

A unique ID has to be Unique across every Thing ID ever in HL and ever going to be entered into HL.  That is allot of Data to make sure we don't clash with. =(

For the Soulknife Bladeskills we should assign the Custom Ability to the Archetype instead of putting in a Pre-Req script looking for the Archetype.  This way only if you have the correct archetype will the Bladeskills even be shown as an option to choose.

Last thing is that we have created a custom component Type for Psion Disciplines.  There is a new editor tab now called "zCommunity->UP Psion Disciplines".  So you don't have to start from scratch.  If you use a text editor you can change the compset="CustomSpec" to compset="PUDisc".  Then remove the script you have on the discipline as its not needed anymore.  Then instead of having to modify the different powers to be associated to the Discipline.  You can assign the Powers on the Discipline instead on the new editor tab.

Thanks Again!

**Comment by drumanagh** [comment]
> I will need to pick up this PDF as I have not heard of it before. =)

Sadly, it's not all that amazing, IMO - I did it all to be comprehensive, but there's only a couple of standout feats/powers and a lot of "this works like existing thing X, except only on undead/incorporeal beings".

> Looking this over quick the first thing that I see we need to fix is the Unique ID's. We need "PU" in all Unique ID's. In example rcPsAuAMan has to become rcPUAuAMan. This adding the PU may seem stupid but its vital to prevent the Pack from clashing with LW stuff.

This one I was unsure about, since the Psionics Augmented line isn't strictly just psionics despite the title (e.g. there's a couple of books that cross over with occult stuff, Path of War material, etc). I can go ahead and update it like that, though.

> For the Soulknife Bladeskills we should assign the Custom Ability to the Archetype instead of putting in a Pre-Req script looking for the Archetype. This way only if you have the correct archetype will the Bladeskills even be shown as an option to choose.

Will do.

> Last thing is that we have created a custom component Type for Psion Disciplines. There is a new editor tab now called "zCommunity->UP Psion Disciplines". So you don't have to start from scratch. If you use a text editor you can change the compset="CustomSpec" to compset="PUDisc". Then remove the script you have on the discipline as its not needed anymore. Then instead of having to modify the different powers to be associated to the Discipline. You can assign the Powers on the Discipline instead on the new editor tab.

I'll go ahead and update it for that.

**Comment by shadowchemosh** [comment]
For the unique ID. If its Path of War we used PW instead.  PU is still around from when it was Psionics Unleashed and its just the standard now.  

These two-digit values also help me when people report errors on the forums or emails or PMs.  The Unique ID can often tell me right away if the issue belongs to the Pack or something "else".  Gamers tend to report "all" errors they see to me. =)

Thanks!

P.S. - In the editor on the 'Tools' section is a place you can enter PU if you want.  Then HL editor will automatically put the PU into Thing IDs for you.  Its sort of handy... =)

**Comment by drumanagh** [comment]
I've made the requested changes, and updated most of the archetype-specific ability choices appropriately. The ones I didn't are for Aegis, since those are on a configurable - is there any reasonably elegant way to limit those in the same way?

**Comment by shadowchemosh** [comment]
> The ones I didn't are for Aegis, since those are on a configurable - is there any reasonably elegant way to limit those in the same way?

What we could do is set the new aegis Custom abilities with a abCategory.? that represents the specific Aegis Archetype.  In example abCategory.arPU0Animi and then modify the Configurable expression to Include these Things.

Honestly as I see you already have all the Pre-Req set for the archetype already I say leave it as is.  It works and we can always adjust it later.

Thanks!

P.S. - I am going to squash and merge this in now...

**Pull request merged**
